version: '3.8'

services:
  app:
    image: laravelphp/php-fpm
    container_name: app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3307:3306"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/html
    networks:
      - app-network

  node:
    image: node:16
    container_name: node
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
